#include "Hardware.h"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/**
 * Initialize the robot.
 */
void initializeRobot()
{
  bFloatDuringInactiveMotorPWM = false;
  motor[motorA] = 100;
  motor[motorB] = 100;
  motor[motorC] = 100;

  return;
}

/**
 *
 */
task main()
{
  bool wheelieBarDown = false;
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase

  while(true)
  {
    getJoystickSettings(joystick);

    if(joy1Btn(8))
    {
      // only allow 20% power
      motor[motorD] = joystick.joy1_y2 * .2;
      motor[motorE] = joystick.joy1_y1 * .2;
      motor[motorA] = 0;
      motor[motorB] = 0;
      motor[motorC] = 100;
    }
    else if(joy1Btn(6))
    {
      // only allow 30% power
      motor[motorD] = joystick.joy1_y2 * .3;
      motor[motorE] = joystick.joy1_y1 * .3;
      motor[motorA] = 0;
      motor[motorB] = 100;
      motor[motorC] = 0;
    }
    else
    {
      // 100% power
      motor[motorD] = joystick.joy1_y2;
      motor[motorE] = joystick.joy1_y1;
      motor[motorA] = 100;
      motor[motorB] = 0;
      motor[motorC] = 0;
    }

    // figure out how to calibrate joystick so we don't have to check a threshold
    if(joystick.joy2_y2 > 10)
    {
      motor[intake] = 30;
    }
    else if(joystick.joy2_y2 < -10)
    {
      motor[intake] = -30;
    }
    else
    {
      motor[intake] = 0;
    }

    // wheelie bar up/down
    if(joystick.joy2_y1 > 10)
    {
      motor[wheelieBar] = 30;
    }
    else if(joystick.joy2_y1 < -10)
    {
      motor[wheelieBar] = -30;
    }
    else
    {
      motor[wheelieBar] = 0;
    }


    if(joy2Btn(2))
    {
      // if joystick button 2 (controller 2) is pressed then servo motor 2 will "open"
      servo[goalArm] = 0;
    }
    else if(joy2Btn(1))
    {
      // if joystick button 1 (controller 1) is pressed then the bridge lowerer/wheelie bar is activated
      /*
      servo[wheelieBar1] = 255;
      servo[wheelieBar2] = 255;
      */
      /*
      if(!wheelieBarDown)
      {
        motor[wheelieBar] = -50;
        wait1Msec(100);
        motor[wheelieBar] = 0;
        wheelieBarDown = true;
      }
      else
      {
        motor[wheelieBar] = 50;
        wait1Msec(100);
        motor[wheelieBar] = 0;
        wheelieBarDown = false;
      }
      */
    }
    else
    {
      //if no buttons are pressed, then the servos will do nothing or go back automatically
      servo[goalArm] = 64;
      /*
      servo[wheelieBar1] = 0;
      servo[wheelieBar2] = 0;
      */
    }
  }
}
