#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    ,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    ,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    ,                     tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



void initializeRobot()
{

  return;
}


task main()
{
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase

  while(true)
  {
    getJoystickSettings(joystick);

    motor[mtr_S1_C1_1] = joystick.joy1_y2;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[mtr_S1_C1_2] = joystick.joy1_y1;         // Motor E is assigned a power level equal to the left analog stick's Y-axis reading.

    /*if(joy2Btn(8) == 1) { // if joystick button 8 (controller 2) is pressed
     motor[mtr_S1_C2_1] = 50; // then the moving goal scorer will take in the batons
    }
    else if(joy2Btn(7) == 1) { // if joystick button 7 (controller 2) is pressed,
    motor[mtr_S1_C2_1] = -50; // then the moving goal scorer will release the batons
    }
    else {
    motor[mtr_S1_C2_1] = 0; // if not pressed, then it'll do absolutely nothing :D
    }*/

    if((motor[mtr_S1_C1_1] > 0 || motor[mtr_S1_C1_2] > 0) && joy1Btn(8) == 1) { // if joystick button 8 (controller 1) is pressed
     motor[mtr_S1_C1_1] = 50;  // then motor D and E will go half speed
     motor[mtr_S1_C1_2] = 50;
    }
    else{ // if not pressed, theeeeen it'll do nothing :D
    }

    if(joy2Btn(2) == 1) {
      servo[srvo_S1_C3_3] = 64; // if joystick button 2 (controller 2) is pressed then servo motor 2 will "open"
    }
    else if(joy1Btn(1) == 1) { // if joystick button 1 (controller 1) is pressed then the bridge lowerer/wheelie bar will go down
    servo[srvo_S1_C3_1] = 255;
    servo[srvo_S1_C3_2] = 255;
    }
    else{
    servo[srvo_S1_C3_3] = 0; //if none of the following buttons are pressed, then the servos will do nothing or go back automatically
    servo[srvo_S1_C3_1] = 0;
    servo[srvo_S1_C3_2] = 0;
    }
  }
}
