#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
#pragma config(Motor,  motorA,          green,        tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          yellow,        tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          red,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     whacker,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    grab,     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    hopper1,     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    hopper2,     tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* $Id: AutonomousModes.c 143 2012-01-21 15:42:12Z 4105 $ */

#define ALL_USER_INPUT
#define GYRO
#define MOVE_GYRO
#define RIGHT_GYRO_TURN
#define LEFT_GYRO_TURN
#define MOVE_TIMED
#define TURN_RIGHT_TIMED
#define TURN_LEFT_TIMED

#include "Autonomous.c"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/**
 * Autonomous modes depending on user input.
 */
task main()
{
  initializeRobot();

  int RM = reversedStart ? -1 : 1;

  // Wait for the beginning of autonomous phase.
  waitForStart();

  StartTask(prettyLights);


  if(startPause)
  {
    wait1Msec(10000);
  }

  // go forward
  if(useGyro)
  {
    moveGyro(RM * MOTOR_FULL, MOVE_OFF_RAMP_TIME);
  }
  else
  {
    moveTimed(RM * MOTOR_FULL, MOVE_OFF_RAMP_TIME);
    wait1Msec(200);
  }

  if(startColor == START_RED)
  {
    // turn left
    if(useGyro)
    {
      leftGyroTurn(-90, MOTOR_FULL);
    }
	  else
	  {
	    turnLeftTimed(MOTOR_FULL, startPosition == START_INSIDE ? LEFT_TURN_TIME : LEFT_OUTSIDE_TURN_TIME);
	    wait1Msec(200);
	  }
	}
	else
	{
	  // turn right
    if(useGyro)
    {
      rightGyroTurn(90, MOTOR_FULL);
    }
	  else
	  {
	    turnRightTimed(MOTOR_FULL, startPosition == START_INSIDE ? RIGHT_TURN_TIME : RIGHT_OUTSIDE_TURN_TIME);
	    wait1Msec(200);
	  }
	}

  if(reversedStart)
  {
    motor[whacker] = -MOTOR_FULL;
    wait1Msec(450);
    motor[whacker] = MOTOR_OFF;
  }

  // move forward
  if(useGyro)
  {
    moveGyro(RM *MOTOR_FULL, startPosition == START_INSIDE ? MOVE_TO_BBALL_TIME : MOVE_OUTSIDE_TO_BBALL_TIME);
  }
  else
  {
    moveTimed(RM * MOTOR_FULL, startPosition == START_INSIDE ? MOVE_TO_BBALL_TIME : MOVE_OUTSIDE_TO_BBALL_TIME);
    wait1Msec(200);
  }

  if(startColor == START_RED)
  {
	  // slight left
	  if(useGyro)
	  {
	    leftGyroTurn(-105, MOTOR_FULL);
	  }
	  else
	  {
	    turnLeftTimed(MOTOR_FULL, startPosition == START_INSIDE ? SLIGHT_LEFT_TIME: SLIGHT_OUTSIDE_LEFT_TIME);
	    wait1Msec(200);
	  }
	}
	else
	{
	  // slight right
	  if(useGyro)
	  {
	    rightGyroTurn(130, MOTOR_FULL);
	  }
	  else
	  {
	    turnRightTimed(MOTOR_FULL, startPosition == START_INSIDE ? SLIGHT_RIGHT_TIME: SLIGHT_OUTSIDE_RIGHT_TIME);
	    wait1Msec(200);
	  }
	}

  if(reversedStart)
  {
    StartTask(BallGrab);
  }
  else
  {
    motor[intake] = MOTOR_FULL;
  }

  // go to the front parking zone
  if(useGyro)
  {
    moveGyro(RM * MOTOR_FULL, 2000);
  }
  else
  {
    moveTimed(RM * MOTOR_FULL, 2000);
  }

  if(startColor == START_RED)
  {
	  // left
	  if(useGyro)
	  {
	    rightGyroTurn(45, MOTOR_FULL);
	  }
	}
	else
	{
	  // slight right
	  if(useGyro)
	  {
	    leftGyroTurn(-15, MOTOR_FULL);
	  }
	}

	if(useGyro)
  {
    moveGyro(RM * MOTOR_FULL, 8000);
  }
  else
  {
    moveTimed(RM * MOTOR_FULL, 8000);
  }
}
