#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  motorA,          green,         tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          yellow,        tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          red,           tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     ballArm,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     clawArm,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     intake,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     spool,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     right,          tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     left,         tmotorNormal, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    clawRelease,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    armRelease,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* $Id$ */

#define ALL_USER_INPUT
#define PARK_MODES
#define GYRO
#define MOVE_GYRO
#define RIGHT_GYRO_TURN
#define LEFT_GYRO_TURN
#define MOVE_TIMED
#define TURN_RIGHT_TIMED
#define TURN_LEFT_TIMED
#define IR_SEEKER
#define BALL_GRAB

#include "Autonomous.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/**
 * Autonomous modes depending on user input.
 */
task main()
{
  disableDiagnosticsDisplay();
  initializeRobot();

  // Wait for the beginning of autonomous phase.
  waitForStart();

  StartTask(prettyLights);

  if(startPause)
  {
    //wait1Msec(10000);
    wait1Msec(5000);
  }

  // go forward
  if(useGyro)
  {
    moveGyro(MOTOR_FULL, MOVE_OFF_RAMP_TIME);
  }
  else
  {
    moveTimed(MOTOR_FULL, MOVE_OFF_RAMP_TIME);
    wait1Msec(200);
  }

  if(startColor == START_RED)
  {
    // turn left
    if(useGyro)
    {
      leftGyroTurn(-90, MOTOR_FULL);
    }
	  else
	  {
	    turnLeftTimed(MOTOR_FULL, startPosition == START_INSIDE ? LEFT_TURN_TIME : LEFT_OUTSIDE_TURN_TIME);
	    wait1Msec(200);
	  }
	}
	else
	{
	  // turn right
    if(useGyro)
    {
      rightGyroTurn(90, MOTOR_FULL);
    }
	  else
	  {
	    turnRightTimed(MOTOR_FULL, startPosition == START_INSIDE ? RIGHT_TURN_TIME : RIGHT_OUTSIDE_TURN_TIME);
	    wait1Msec(200);
	  }
	}

  motor[ballArm] = MOTOR_FULL;
  wait1Msec(450);
  motor[ballArm] = MOTOR_OFF;

  // move forward
  if(useGyro)
  {
    moveGyro(MOTOR_FULL, startPosition == START_INSIDE ? MOVE_TO_BBALL_TIME : MOVE_OUTSIDE_TO_BBALL_TIME);
  }
  else
  {
    moveTimed(MOTOR_FULL, startPosition == START_INSIDE ? MOVE_TO_BBALL_TIME : MOVE_OUTSIDE_TO_BBALL_TIME);
    wait1Msec(200);
  }

  if(startColor == START_RED)
  {
	  // slight left
	  if(useGyro)
	  {
	    leftGyroTurn(-115, MOTOR_FULL);
	  }
	  else
	  {
	    turnLeftTimed(MOTOR_FULL, startPosition == START_INSIDE ? SLIGHT_LEFT_TIME: SLIGHT_OUTSIDE_LEFT_TIME);
	    wait1Msec(200);
	  }
	}
	else
	{
	  // slight right
	  if(useGyro)
	  {
	    rightGyroTurn(125, MOTOR_FULL);
	  }
	  else
	  {
	    turnRightTimed(MOTOR_FULL, startPosition == START_INSIDE ? SLIGHT_RIGHT_TIME: SLIGHT_OUTSIDE_RIGHT_TIME);
	    wait1Msec(200);
	  }
	}

  StartTask(BallGrab);

  if(bBallPark == PARK_FRONT)
  { // go to the front parking zone
	  if(useGyro)
	  {
	    moveGyro(MOTOR_FULL, MOVE_TO_CORNER_TIME);
	  }
	  else
	  {
	    moveTimed(MOTOR_FULL, MOVE_TO_CORNER_TIME);
	  }
	}
  else //if(bBallPark == PARK_BACK)
  { // go to the back parking zone
    if(useGyro)
    {
      moveGyro(MOTOR_FULL, 1000);
    }
    else
    {
      moveTimed(MOTOR_FULL, 1000);
    }

    if(startColor == START_RED)
    {
	    if(useGyro)
	    {
	      rightGyroTurn(45, MOTOR_FULL);
	    }
	  }
	  else
	  {
	    if(useGyro)
	    {
	      leftGyroTurn(-15, MOTOR_FULL);
	    }
	  }

	  if(robotPark == PARK_FRONT)
    { // leave the bowling ball in the back and park in the front
      motor[ballArm] = MOTOR_FULL;
      wait1Msec(450);
      motor[ballArm] = MOTOR_OFF;
      if(useGyro)
      {
        moveGyro(MOTOR_FULL, 3000);
      }
      else
      {
        moveTimed(MOTOR_FULL, 3000);
      }

      wait1Msec(500);

      if(useGyro)
      {
        moveGyro(-MOTOR_FULL, 2500);
      }
      else
      {
        moveTimed(-MOTOR_FULL, 2500);
      }

      for(int i = 0; i < 3; i++)
      {
        turnToIRBeacon(MOTOR_FULL);

        if(useGyro)
        {
          moveGyro(-MOTOR_FULL, 1000);
        }
        else
        {
          moveTimed(-MOTOR_FULL, 1000);
        }
      }
    }
    else
    { // bowling ball and robot in the back
      if(useGyro)
      {
        moveGyro(MOTOR_FULL, 3000);
      }
      else
      {
        moveTimed(MOTOR_FULL, 3000);
      }
    }
  }
}
