#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
#pragma config(Motor,  motorA,          green,         tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          yellow,        tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          red,           tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     whacker,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    grab,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    hopper1,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    hopper2,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S2,     HTGYRO,              sensorI2CCustom)
//#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
//#pragma config(Sensor, S2,     HTGYRO,              sensorLowSpeed)

/* $Id: O-Back.c 92 2011-12-15 23:08:48Z 4105 $ */

#define GYRO
#define RIGHT_GYRO_TURN
#define LEFT_GYRO_TURN

#include "Autonomous.c"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/**
 * Do nothing.
 */
task main()
{
  initializeRobot();

  // Wait for the beginning of autonomous phase.
  //waitForStart();

  StartTask(getHeading);
  StartTask(prettyLights);

  wait1Msec(2000);

  leftGyroTurn(270, MOTOR_FULL);
  wait1Msec(1000);
  leftGyroTurn(180, MOTOR_FULL);

  /*
  rightGyroTurn(90, MOTOR_FULL);
  wait1Msec(5000);
  rightGyroTurn(180, MOTOR_FULL);
  */

  wait1Msec(30000);
}
