#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
#pragma config(Motor,  motorA,          green,         tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          yellow,        tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          red,           tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     whacker,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    grab,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    hopper1,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    hopper2,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S2,     HTGYRO,              sensorI2CCustom)
//#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
//#pragma config(Sensor, S2,     HTGYRO,              sensorLowSpeed)

/* $Id$ */

#define GYRO
#define RIGHT_GYRO_TURN
#define LEFT_GYRO_TURN
#define MOVE_GYRO
#define MOVE_TIMED

#include "Autonomous.c"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/**
 * Do nothing.
 */
task main()
{
  initializeRobot();

  // Wait for the beginning of autonomous phase.
  //waitForStart();

  wait1Msec(1000);

  StartTask(prettyLights);

  leftGyroTurn(-90, MOTOR_FULL);
  wait1Msec(1000);
  rightGyroTurn(0, MOTOR_FULL);
  wait1Msec(1000);

  return;
  //moveGyro(MOTOR_FULL, 4000);
  moveTimed(MOTOR_FULL, 4000);
  wait1Msec(100);
  return;

  moveGyro(MOTOR_FULL, 2200);
  wait1Msec(100);
  leftGyroTurn(-90, MOTOR_FULL);
  wait1Msec(100);
  moveGyro(MOTOR_FULL, 1000);

  wait1Msec(30000);
}
