#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTAC,                sensorLowSpeed)
#pragma config(Motor,  motorA,          motorA,        tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          motorB,        tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          motorC,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     intake,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     wheelieBar,    tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    goalCapture1,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    goalCapture2,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    goalArm,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* $Id$ */

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Autonomous.c"

/**
 * Starting on the left side, traverse the bridge.
 */
task main()
{
  initializeRobot();

  HTACreadAllAxes(HTAC, xAxis, yAxis, zAxis);

  // Wait for the beginning of autonomous phase.
  waitForStart();

  ClearTimer(T1);

  HTACreadAllAxes(HTAC, xLevel, yAxis, zAxis);

  motor[motorB] = 0;
  motor[motorC] = 0;

  StartTask(balanceLEDIndicate);

  rightHalfTurn();
  wait1Msec(200);

  move(L_BRIDGE_APPROACH, 30);
  wait1Msec(200);

  rightHalfTurn();
  wait1Msec(200);

  rightTurn();
  wait1Msec(200);

  motor[motorE] = -30;
  wait1Msec(L_BRIDGE_ADJUST_TIME);
  motor[motorE] = 0;
  nMotorEncoder[motorE] = 0;
  nMotorEncoder[motorD] = 0;

  moveTimed(L_BRIDGE_ADJUST, -30, 300);
  wait1Msec(200);

  /* wheelie bar */
  wheelieBarDown();
  wait1Msec(300);

  moveTimed(BR_GET_ON, -30, 300);
  wait1Msec(200);

  if(!onBridge())
  {
    retryBridgeApproach();
  }

  wheelieBarUp();
  wait1Msec(200);

  move(BR_TO_CENTER, -30);
  wait1Msec(500);

  bridgeBalanceStabilize();

  // could not balance, move off of bridge
  move(BR_MOVE_OFF, -30);

  wait1Msec(30000);
}
