#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
#pragma config(Motor,  motorA,          green,        tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          yellow,        tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          red,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     whacker,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    grab,     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    hopper1,     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    hopper2,     tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* $Id: BI-Front.c 106 2012-01-02 23:12:27Z 4105 $ */

#define GYRO
#define LEFT_GYRO_TURN
#define MOVE_GYRO

#include "Autonomous.c"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/**
 * Starting on red on the inside, drive to the front parking area.
 */
task main()
{
  initializeRobot();

  // Wait for the beginning of autonomous phase.
  waitForStart();

  StartTask(prettyLights);

  // go forward
  moveGyro(MOTOR_FULL, MOVE_OFF_RAMP_TIME);
  //wait1Msec(200);

  // turn left
  leftGyroTurn(-90, MOTOR_FULL);
  //wait1Msec(200);

  // move forward
  moveGyro(MOTOR_FULL, MOVE_TO_BBALL_TIME);
  //wait1Msec(200);

  // slight left
  leftGyroTurn(-105, MOTOR_FULL);
  //wait1Msec(200);

  //motor[intake] = MOTOR_FULL;

  // go to the front parking zone
  moveGyro(MOTOR_FULL, MOVE_TO_CORNER_TIME);
}
